package co.d3s.ylt.renate.player;

import co.d3s.ylt.renate.network.protocol.PacketType;
import co.d3s.ylt.renate.player.protocol.Packet000KeepAlive;
import co.d3s.ylt.renate.player.protocol.Packet001Login;
import co.d3s.ylt.renate.player.protocol.Packet002Handshake;
import co.d3s.ylt.renate.player.protocol.Packet003Chat;
import co.d3s.ylt.renate.player.protocol.Packet004UpdateTime;
import co.d3s.ylt.renate.player.protocol.Packet005EntityEquipment;
import co.d3s.ylt.renate.player.protocol.Packet006SpawnPosition;
import co.d3s.ylt.renate.player.protocol.Packet007UseEntity;
import co.d3s.ylt.renate.player.protocol.Packet008UpdateHealth;
import co.d3s.ylt.renate.player.protocol.Packet009Respawn;
import co.d3s.ylt.renate.player.protocol.Packet010Flying;
import co.d3s.ylt.renate.player.protocol.Packet011PlayerPosition;
import co.d3s.ylt.renate.player.protocol.Packet012PlayerLook;
import co.d3s.ylt.renate.player.protocol.Packet013PlayerLookMove;
import co.d3s.ylt.renate.player.protocol.Packet014BlockDig;
import co.d3s.ylt.renate.player.protocol.Packet015Place;
import co.d3s.ylt.renate.player.protocol.Packet016BlockItemSwitch;
import co.d3s.ylt.renate.player.protocol.Packet017;
import co.d3s.ylt.renate.player.protocol.Packet018ArmAnimation;
import co.d3s.ylt.renate.player.protocol.Packet019EntityAction;
import co.d3s.ylt.renate.player.protocol.Packet020NamedEntitySpawn;
import co.d3s.ylt.renate.player.protocol.Packet021PickupSpawn;
import co.d3s.ylt.renate.player.protocol.Packet022Collect;
import co.d3s.ylt.renate.player.protocol.Packet023VehicleSpawn;
import co.d3s.ylt.renate.player.protocol.Packet024MobSpawn;
import co.d3s.ylt.renate.player.protocol.Packet025EntityPainting;
import co.d3s.ylt.renate.player.protocol.Packet026AddExpOrb;
import co.d3s.ylt.renate.player.protocol.Packet028EntityVelocity;
import co.d3s.ylt.renate.player.protocol.Packet029DestroyEntity;
import co.d3s.ylt.renate.player.protocol.Packet030Entity;
import co.d3s.ylt.renate.player.protocol.Packet031RelEntityMove;
import co.d3s.ylt.renate.player.protocol.Packet032EntityLook;
import co.d3s.ylt.renate.player.protocol.Packet033RelEntityMoveLook;
import co.d3s.ylt.renate.player.protocol.Packet034EntityTeleport;
import co.d3s.ylt.renate.player.protocol.Packet035HeadLook;
import co.d3s.ylt.renate.player.protocol.Packet038EntityStatus;
import co.d3s.ylt.renate.player.protocol.Packet039AttachEntity;
import co.d3s.ylt.renate.player.protocol.Packet040EntityMetadata;
import co.d3s.ylt.renate.player.protocol.Packet041MobEffect;
import co.d3s.ylt.renate.player.protocol.Packet042RemoveMobEffect;
import co.d3s.ylt.renate.player.protocol.Packet043SetExperience;
import co.d3s.ylt.renate.player.protocol.Packet050PreChunk;
import co.d3s.ylt.renate.player.protocol.Packet051MapChunk;
import co.d3s.ylt.renate.player.protocol.Packet052MultiBlockChange;
import co.d3s.ylt.renate.player.protocol.Packet053BlockChange;
import co.d3s.ylt.renate.player.protocol.Packet054PlayNoteBlock;
import co.d3s.ylt.renate.player.protocol.Packet060Explosion;
import co.d3s.ylt.renate.player.protocol.Packet061;
import co.d3s.ylt.renate.player.protocol.Packet070Bed;
import co.d3s.ylt.renate.player.protocol.Packet071Weather;
import co.d3s.ylt.renate.player.protocol.Packet100OpenWindow;
import co.d3s.ylt.renate.player.protocol.Packet101CloseWindow;
import co.d3s.ylt.renate.player.protocol.Packet102WindowClick;
import co.d3s.ylt.renate.player.protocol.Packet103SetSlot;
import co.d3s.ylt.renate.player.protocol.Packet104WindowItems;
import co.d3s.ylt.renate.player.protocol.Packet105CraftProgressBar;
import co.d3s.ylt.renate.player.protocol.Packet106Transaction;
import co.d3s.ylt.renate.player.protocol.Packet107SetCreativeSlot;
import co.d3s.ylt.renate.player.protocol.Packet130UpdateSign;
import co.d3s.ylt.renate.player.protocol.Packet131;
import co.d3s.ylt.renate.player.protocol.Packet195Spout;
import co.d3s.ylt.renate.player.protocol.Packet200Statistic;
import co.d3s.ylt.renate.player.protocol.Packet201PlayerInfo;
import co.d3s.ylt.renate.player.protocol.Packet202Abilities;
import co.d3s.ylt.renate.player.protocol.Packet254GetInfo;
import co.d3s.ylt.renate.player.protocol.Packet255KickDisconnect;

public class PlayerPacketType extends PacketType {
	{
		add(0, true, true, Packet000KeepAlive.class);
		add(1, true, true, Packet001Login.class);
		add(2, true, true, Packet002Handshake.class);
		add(3, true, true, Packet003Chat.class);
		add(4, true, false, Packet004UpdateTime.class);
		add(5, true, false, Packet005EntityEquipment.class);
		add(6, true, false, Packet006SpawnPosition.class);
		add(7, false, true, Packet007UseEntity.class);
		add(8, true, false, Packet008UpdateHealth.class);
		add(9, true, true, Packet009Respawn.class);
		add(10, true, true, Packet010Flying.class);
		add(11, true, true, Packet011PlayerPosition.class);
		add(12, true, true, Packet012PlayerLook.class);
		add(13, true, true, Packet013PlayerLookMove.class);
		add(14, false, true, Packet014BlockDig.class);
		add(15, false, true, Packet015Place.class);
		add(16, false, true, Packet016BlockItemSwitch.class);
		add(17, true, false, Packet017.class);
		add(18, true, true, Packet018ArmAnimation.class);
		add(19, false, true, Packet019EntityAction.class);
		add(20, true, false, Packet020NamedEntitySpawn.class);
		add(21, true, false, Packet021PickupSpawn.class);
		add(22, true, false, Packet022Collect.class);
		add(23, true, false, Packet023VehicleSpawn.class);
		add(24, true, false, Packet024MobSpawn.class);
		add(25, true, false, Packet025EntityPainting.class);
		add(26, true, false, Packet026AddExpOrb.class);
		add(28, true, false, Packet028EntityVelocity.class);
		add(29, true, false, Packet029DestroyEntity.class);
		add(30, true, false, Packet030Entity.class);
		add(31, true, false, Packet031RelEntityMove.class);
		add(32, true, false, Packet032EntityLook.class);
		add(33, true, false, Packet033RelEntityMoveLook.class);
		add(34, true, false, Packet034EntityTeleport.class);
		add(35, true, true,  Packet035HeadLook.class); //TODO: see if it actually goes both ways
		add(38, true, false, Packet038EntityStatus.class);
		add(39, true, false, Packet039AttachEntity.class);
		add(40, true, false, Packet040EntityMetadata.class);
		add(41, true, false, Packet041MobEffect.class);
		add(42, true, false, Packet042RemoveMobEffect.class);
		add(43, true, false, Packet043SetExperience.class);
		add(50, true, false, Packet050PreChunk.class);
		add(51, true, false, Packet051MapChunk.class);
		add(52, true, false, Packet052MultiBlockChange.class);
		add(53, true, false, Packet053BlockChange.class);
		add(54, true, false, Packet054PlayNoteBlock.class);
		add(60, true, false, Packet060Explosion.class);
		add(61, true, false, Packet061.class);
		add(70, true, false, Packet070Bed.class);
		add(71, true, false, Packet071Weather.class);
		add(100, true, false, Packet100OpenWindow.class);
		add(101, true, true, Packet101CloseWindow.class);
		add(102, false, true, Packet102WindowClick.class);
		add(103, true, false, Packet103SetSlot.class);
		add(104, true, false, Packet104WindowItems.class);
		add(105, true, false, Packet105CraftProgressBar.class);
		add(106, true, true, Packet106Transaction.class);
		add(107, true, true, Packet107SetCreativeSlot.class);
		add(130, true, true, Packet130UpdateSign.class);
		add(131, true, false, Packet131.class);
		add(200, true, false, Packet200Statistic.class);
		add(201, true, false, Packet201PlayerInfo.class);
		add(202, true, true, Packet202Abilities.class);
		add(254, false, true, Packet254GetInfo.class);
		add(255, true, true, Packet255KickDisconnect.class);

		add(195, true, true, Packet195Spout.class);
	}
}
